<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
function disqus_perm() {
  return array(
    'administer disqus',
    'view disqus comments',
  );
}

/**
 * Implementation of hook_menu().
 */
function disqus_menu() {
  $items = array();
  $items['admin/settings/disqus'] = array(
    'title' => 'Disqus',
    'access arguments' => array('administer disqus'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('disqus_admin_settings'),
    'file' => 'disqus.admin.inc'
  );
  return $items;
}

/**
 * Implementation of hook_nodeapi().
 */
function disqus_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
      // Don't show in the teaser view
      if (!$a3) {
        // See if we're to display Disqus
        $types = variable_get('disqus_nodetypes', array());
        if (!empty($types[$node->type]) && user_access('view disqus comments')) {
          // Check which Disqus domain to use
          $domain = variable_get('disqus_domain', '');
          if (!empty($domain)) {
            // Build the message excerpt
            $message = nl2br($node->teaser);
            $message = str_replace("\r", ' ', $message);
            $message = str_replace("\n", ' ', $message);
            $message = strip_tags($message, '<a>');
            $message = check_plain($message);

            // Build the title
            $title = check_plain($node->title);

            // Inject the script
            $disqus = "<script type=\"text/javascript\">var disqus_title = \"$title\";var disqus_message = \"$message\";</script><div id=\"disqus_thread\"></div><script type=\"text/javascript\" src=\"http://disqus.com/forums/$domain/embed.js\"></script><noscript><a href=\"http://$domain.disqus.com/?url=ref\">View the forum thread.</a></noscript>";
            $node->content['disqus'] = array(
              '#value' => $disqus,
              '#weight' => 10,
            );
          }
        }
      }
    break;
  }
}


/**
 * Implementation of hook_link().
 */
function disqus_link($type, $node = NULL, $teaser = FALSE) {
  $links = array();
  if ($type == 'node' && $teaser == TRUE) {
    $types = variable_get('disqus_nodetypes', array());
    if (!empty($types[$node->type]) && user_access('view disqus comments')) {
      $links['disqus_comments'] = array(
        'title' => t('Comments'),
        'href' => "node/$node->nid",
        'attributes' => array('title' => t('Jump to the comments of this posting.')),
        'fragment' => 'disqus_thread',
      );
      static $disqus_js_added = FALSE;
      if ($disqus_js_added === FALSE) {
        $disqus_js_added = TRUE;
        $domain = variable_get('disqus_domain', '');
        $disqus_js = <<<EOT
//<[CDATA[
(function() {
    var links = document.getElementsByTagName('a');
    var query = '?';
    for(var i = 0; i < links.length; i++) {
      if(links[i].href.indexOf('#disqus_thread') >= 0) {
        query += 'url' + i + '=' + encodeURIComponent(links[i].href) + '&';
      }
    }
    document.write('<script type="text/javascript" src="http://disqus.com/forums/$domain/get_num_replies.js' + query + '"></' + 'script>');
  })();
//]]>
EOT;
        drupal_add_js($disqus_js, 'inline', 'footer');
      }
    }
  }
  return $links;
}
