<?php
// $Id$

/**
 * @file
 * Provides any required installation or upgrade path requirements.
 */

/**
 * Implements hook_uninstall().
 */
function disqus_uninstall() {
  variable_del('disqus_domain');
  variable_del('disqus_userapikey');
  variable_del('disqus_nodetypes');
  variable_del('disqus_developer');
}

/**
 * Updates from Drupal 6 to 7.
 */
function disqus_update_7000() {
  // Nothing.
}
